version: '3.4'

services:  
  authentification:
    container_name: api_container
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: C:\Projects\Extra\ConnectEventsProviders\EventsServices\Events\Dockerfile


  #events:
  #  container_name: events_container
  #  image: ${DOCKER_REGISTRY-}events
  #  build:
  #    context: .
  #    dockerfile: C:\Projects\Extra\ConnectEventsProviders\EventsServices\Events\Dockerfile
  #  ports:
  #    - "49256:443"

  