version: '3.4'

services:
    authentification:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        ports: 
            - "5000:80"
            - "5001:81"

    events:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        ports: 
            - "5002:80"
            - "5003:81"
    providers:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        ports: 
            - "5004:80"
            - "5005:81"
    requests:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
        ports: 
            - "5006:80"
            - "5007:81"